### ISSUE TITLE
using stockfish as a shared library

### ISSUE THREAD

**Issue by pavanjoshi914** [ab-chesspad/ChessPad#3]
I saw your efforts regarding converting stockfish so that it can be used as a shared library! first of all, I appreciate the efforts you put to do this.

however I wanted to know the processing of communicating with this shared library in Unity for android platform and using C#. any idea of doing this will be a great starting point to me

**Comment by ab-chesspad** [comment]
Sorry, this project has been dormant for a while and I just noticed your message.
Unfortunately I am not familiar with Unity and it's been long time since I used C#.
I am working on ChessPad major update now. Anyway, you may want to use ChessPad/ChessPadApp/src/main/cpp/stockfishlib.cpp and ChessPad/ChessPadApp/src/main/java/com/ab/pgn/uci/Stockfish.java as a reference for JNI layer to access C/C++ programs. I have no clue how this can be done on C#.

**Comment by ab-chesspad** [comment]
closed because of inactivity
